// Generated by CoffeeScript 1.4.0
(function() {
  var logData, subscribeTopic;

  logData = function(topics, data) {
    console.log('from subscribed');
    return console.log(topics + ': ' + data);
  };

  subscribeTopic = pubsub.subscribe('user', logData);

  pubsub.publish('user', {
    foo: 'bar'
  });

  setTimeout(function() {
    return pubsub.unsubscribe(initSubscriber, 0);
  });

}).call(this);
